<?php 
	print '
	<h1>O meni</h1>
	<h2 id="podnaslov">Živim za fotografiranje. Živim od fotografiranja. Mislim da je to upravo najveća sreća, jer baviti se onim što volim i živjeti od toga čini me neizmjerno sretnim.</h2>
    <video width="50%" controls poster="video/cover.jpg" >
        <source src="video/wedding-book-majaandbranko.mp4" type="video/mp4">
        Your browser does not support HTML5 video.
        </video>
    <p>Vjerujte u sebe. Ne odustajte. Mislim da je to najbolji sažetak ovog dijela ”o meni”. U osnovnoj školi sam bio prosječan učenik, tako da sam jedva upisao srednju školu koju sam želio. Nedostajala su mi četiri boda da bih došao do praga, ali sam se svejedno uspio upisati Željezničku tehničku školu (danas Tehničku školu Zagreb), smjer Tehničar za elektroniku. Od toga da sam jedva upao sam došao do toga da sam bio među boljim učenicima, tako da sam tri razreda završio odličnim uspjehom. Negdje sredinom srednje me novinarstvo zainteresiralo. Što baš i nema veze sa školom u koju sam išao. Ne mora sve u životu na prvu ni biti logično. Krenuo sam pisati za dnevne novine Sportske novosti, a nakon godinu-dvije sam na terenu sreo jednog kolegu. On mi je rekao da umjesto honorara samo za tekst mogu dobiti i dupli honorar ako mi objave i fotografiju. Odvojio sam petstotinjak kuna, otišao u Lidl u kojem sam kupio svoj prvi digitalni fotoaparat. S njim sam uspio snimiti neke od fotografija koje su završile u novinama. Nisu to bile nikakve vrhunske fotografije, ali su bile vrhunski poticaj.</p>
    <h2 id="prekid">Obrazovanje</h2>
    <p>Nakon srednje škole sam upisao preddiplomski studij novinarstva na Fakultetu političkih znanosti u Zagrebu koji sam završio 2011. godine. U sklopu studija s fotografijom sam se najčešće susretao na kolegiju Fotonovinarstvo. Fotografiranjem se aktivno počinjem baviti 2009. godine kada sam kupio svoj prvi DSLR. Bio je to Sony A350X s kojim sam se upustio u fotografske vode, a roditelji su za njega digli kredit koji sam ja onda kroz studentske poslove i otplaćivao. U većini zagrebačkih noćnih klubova tada sam radio kao fotograf, a isto tako sam stekao i neke od većih klijenata za razna fotografiranja, od hrane, pića, do događanja. Na diplomskom studiju sam diplomirao u listopadu 2013. godine. Titula magistra novinarstva otvorila je mnoga polja, posebno u svijetu fotografije.</p>
    <p>Kroz moju dosadašnju fotografsku karijeru sam radio za jako puno klijenata. Teško mi je izdvojiti neke od njih. U pitanju su brojni svjetski poznati brendovi, kao i male lokalne tvrtke. Na kraju svakog posla najvažnije je da klijenti budu zadovoljni. I u svakom su poslu bili zadovoljni, što smatram najvećim dobitkom. Moto moje internetske prezentacije glasi: Sve što nas okružuje idealan je kadar. Samo ga treba znati iskoristiti. Upravo se tom logikom i vodim kroz svoje fotografije, jer sve što nas okružuje zanimljivo je u jednoj mjeri i samo treba pronaći pravi način za zabilježiti taj kadar. Posebno bih izdvojio da sam u 2021. godini radio za UEFU kao službeni fotograf na završnici futsal Lige prvaka. Doći do toga nije bilo nimalo lagano, ali je sve to rezultat mog dugogodišnjeg fotografiranja i referenci koje sam skupio.</p>
    <h2>Knjiga <em>U vrtlogu vjenčanja</em></h2>
    <p>U 2020. godini izdao sam stručnu fotografsku knjigu U vrtlogu vjenčanja. Ona obuhvaća sve vezano za fotografiranje vjenčanja, a kritike na knjigu za sada su bile odlične. Na našim prostorima nije postojala takva stručna knjiga, tako da sam vrijeme u koroni iskoristio kako bih pomogao kolegama. Ako već ja imam privilegiju živjeti od fotografiranja, onda je ovo bio moj ”poklon” za sve one koji će jednako odlučnu krenuti putem kojim sam i ja krenuo.</p>
    <p>Izlagao sam na raznim izložbama, a uvijek su u pitanju bile grupne izložbe. Bio sam gost predavač na raznim fotografskim radionicama, što mi je isto tako predstavljalo posebno veliku čast jer sam bio prepoznat od fotografske zajednice. Također sam organizirao i vlastite fotografske radionice, posebno na temu fotografiranja vjenčanja.</p>
    <p>Živim za fotografiranje. Živim od fotografiranja. Mislim da je to upravo najveća sreća, jer baviti se onim što volim i živjeti od toga čini me neizmjerno sretnim. Kada primim fotoaparat u ruke i krenem na teren, to je moćan osjećaj. Posebno znam da radim pravu stvar zato jer za neka fotografiranja imam određenu tremu. Sve dok je tako, dok vidim da mi je stalo, bit će dobro i bavit ću se fotografiranjem.</p>
    <h2>Saznaj više</h2>
    <p>Kada ste već došli do ovog dijela, pretpostavljam da vas zanima općenito više vezano za fotografiranje. Zato bih se na kraju osvrnuo na edukaciju, jer se nadam da bi ovaj dio mogao pomoći budućim fotografima. Preporučio bih Scotta Kelbyja i njegove serije knjiga ”Digitalna fotografija”. Korisna su i Algebrina izdanja knjiga koje pokrivaju razna područja u fotografiji. Od pisane literature bih još korisnim izdvojio ”Džepni fotografski priručnik” autora Živojina Jeremića. Knjiga je napisana još osamdesetih godina prošlog stoljeća, pa je isključivo orijentirana na analognu fotografiju. Uz pregršt knjiga u velikoj su mi mjeri pomogli internetski portali, snimci na YouTube kanalu, filmovi i sličan materijal. Karl Taylor ima odličan video materijal koji pokriva gotovo sva područja fotografije, a njegovi materijali vezani za Photoshop su nešto što bih svakome preporučio. Za Photoshop ne zaboravite na PHlearn.</p>
    
    <script>
        let main = Array.from(document.getElementsByTagName("main"))[0];
        main.className = "omeni";
    </script>';
?>